openapi: 3.0.3
info:
  title: Peer Review API
  version: "0.1.3"
servers:
  - url: http://localhost:8080
paths:
  /me/submissions:
    get: { summary: My submissions counts, responses: { '200': { description: ok } } }
  /me/assignments:
    get: { summary: My reviewer todo, responses: { '200': { description: ok } } }
  /submissions:
    post: { summary: Create submission meta, responses: { '201': { description: created } } }
  /submissions/{id}/assignments:
    get: { summary: Counts for student / list for instructor, responses: { '200': { description: ok } } }
  /assign:
    post: { summary: Assign or revive canceled assignment, responses: { '200': { description: already }, '201': { description: created } } }
  /reviews:
    post: { summary: Create review; ML stores outputs separately, responses: { '201': { description: created } } }
  /instructor/overview:
    get: { summary: Cohort-level weekly aggregates, responses: { '200': { description: ok } } }
